version: "3.8"
services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web_api

